name: Deploy Frontend to Hostinger

on:
  push:
    branches:
      - deploy-hostinger # branch tempat kamu deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install dependencies di dalam folder frontend
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install

      # Build project React di folder frontend
      - name: Build Project
        working-directory: ./frontend
        run: CI=false npm run build

      # Upload hasil build ke Hostinger via FTP
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftp
          local-dir: ./frontend/build/
          server-dir: domains/inodstudiomanager.com/public_html/test/
          # server-dir: ${{ secrets.FTP_DIRECTORY }}
          dangerous-clean-slate: true
